### ISSUE TITLE
node connects after channel creation failed because node was unconnected (race condition?)

### ISSUE THREAD

**Issue by rsnel** [lightninglabs/pool#143]
I have logs for a failed channel creation (I can send full logs in a private message).

PEER= private key of peer (always the same peer)

in chronological order

poold:  [INF] FNDG: Batch(xxx): opening channels for 1 matched orders
poold: [INF] FNDG: Registering funding shim for Order(type=Ask, amt=x BTC, nonce=xx
lnd: [ERR] RPCS: unable to open channel to NodeKey(PEER): peer PEER is not inline
lnd: [ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: peer PEER is not online
poold: [ERR] FNDG: unable to read chan open update event from node PEER, going to reject channel: rpc error: code = Unknown desc = peer  PEER is not online
lnd:  [INF] SRVR: New inbound connection from IP_OF_PEER
lnd: [INF] SRVR: Finalizing connection to PEER@IP_OF_PEER
lnd: [ERR] RPCS: [/lnrpc.Lightning/SubscribePeerEvents]: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called

It looks like channel creation would have succeeded if the connection from PEER would have come earlier.

**Comment by Roasbeef** [comment]
So these are logs from both lnd and poold right? Do you have rough timestamps available? Is the node only listening over Tor? Was the other node connecting only advertising a hidden service?

**Comment by rsnel** [comment]
The node doesn't use Tor (I disabled it rule it out as a source of problems). Yes, the logs are from poold and lnd.

Timestamps:

Everything happens in the same second (so h:m:s is identical everywhere). The error and the connection event are really close together.

h:m:s.450 poold: [INF] FNDG: Batch(xxx): opening channels for 1 matched orders
h:m:s.451 poold: [INF] FNDG: Registering funding shim for Order(type=Ask, amt=x BTC, nonce=xx
h:m:s.492 lnd: [ERR] RPCS: unable to open channel to NodeKey(PEER): peer PEER is not inline
h:m:s.492 lnd: [ERR] RPCS: [/lnrpc.Lightning/OpenChannel]: peer PEER is not online
h:m:s.492 poold: [ERR] FNDG: unable to read chan open update event from node PEER, going to reject channel: rpc error: code = Unknown desc = peer PEER is not online
h:m:s.504 lnd: [INF] SRVR: New inbound connection from IP_OF_PEER
h:m:s.505 lnd: [INF] SRVR: Finalizing connection to PEER@IP_OF_PEER
h:m:s.506 lnd: [ERR] RPCS: [/lnrpc.Lightning/SubscribePeerEvents]: rpc error: code = Internal desc = transport: transport: the stream is done or WriteHeader was already called

**Comment by guggero** [comment]
I assume you're on the latest version of Pool? We recently changed the timeouts for the connection process.

From the point of view of `poold`, your node is running Tor if the URI field of `lncli getinfo` shows a `.onion` address. In that case, we try to establish the connection from both sides (maker->taker and taker->maker), in the batch preparation stage.
So it would be interesting to see the logs from a few seconds before. Does your node try to connect out? Does that fail?

**Comment by rsnel** [comment]
I use pool(d)  0.3.2-alpha. My node does not run Tor. 

Grepping the log on de node ID of the peer (PEER) gives:

- a NodeAnnouncement(node=PEER, timestamp) to other node

- and then 5.5 hours later: the 'unable to open channel'

so no connection attempt was done by my node

In the meantime I have a couple of working channels from the pool, so that's great. I have gotten no more failed 'Registering funding shim', but a couple 'preparing channel funding for 1 orders' with no followup (other than a 'unable to abandon channel' when the same batch is repeated).

**Comment by halseth** [comment]
@rsnel You should remove your Tor address from your lnd config if you are not listening on tor anymore:
`externalip=<tor-addr>`

You can check that you are not advertising by doing `lncli getinfo`. Only your non-tor address should show up.

**Comment by rsnel** [comment]
@halseth My tor address is not in my lnd config. `lncli getinfo` only lists my ipv4 and ipv6 addresses.

In the meantime I have upgraded to the new version 0.3.3-alpha. I have not seen this issue again.

**Comment by halseth** [comment]
> @halseth My tor address is not in my lnd config. `lncli getinfo` only lists my ipv4 and ipv6 addresses.
> 
> In the meantime I have upgraded to the new version 0.3.3-alpha. I have not seen this issue again.

Awesome, please report the issue with more logs if you hit it again :)

**Comment by halseth** [comment]
Closing per https://github.com/lightninglabs/pool/issues/143#issuecomment-727903687
