### ISSUE TITLE
high fee although mempool is not very full

### ISSUE THREAD

**Issue by kccheung** [lightninglabs/pool#144]
As titled, pool seems to use high fee rate during account creation although mempool is not very full.

-- Account Funding Details --
Amount: 0.03 BTC
Confirmation target: 6 blocks
Fee rate (estimated): 122.7 sat/vByte
Total miner fee (estimated): 0.00043913 BTC
Confirm account (yes/no):

However, in this weekend I checked other fee estimation site and it gives me:

5% | 20% | 50% | 80% | 95%
-- | -- | -- | -- | --
2.2 | 2.2 | 2.7 | 3.3 | 24.5

Can I set lower sat per byte during pool account creation?

**Comment by Roasbeef** [comment]
> Can I set lower sat per byte during pool account creation?

Yes. See `pool accounts new -h`
