### ISSUE TITLE
Convertion between satoshi and units issue

### ISSUE THREAD

**Issue by Pantamis** [lightninglabs/pool#145]
Thanks for making pool ! I am trying it in LiT now that onchain fees are lower.

I submit an ask order but I found a weird issue with satoshis and units convertion:

`$ pool --rpcserver=localhost:10009 orders submit ask 6500000 [trader key] ...`
`> [pool] unable to parse order params: minimum channel amount 0.0065 BTC must be a multiple of 0.001 BTC`

Notice that the amount 6500000 = 6 500 000 satoshis is displayed as 0.0065 BTC, which is a mistake (it must be 0.065 BTC).

However this order is accepted and amount in BTC are correct:

`$ pool --rpcserver=localhost:10009 orders submit ask 6000000`
`> Ask Amount: 0.06 BTC`
`...`

**Comment by guggero** [comment]
Thank you for the report. Just to clarify, this isn't a conversion error. The `minimum channel amount` is the smallest amount you want to have matched in one match. You can set it by specifying `--min_chan_amt`. The default value is 10% of the full order amount, which is the 0.0065 BTC that you saw.
What should be fixed though is that those default 10% should always be rounded up to be a multiple of the order unit, so in your case 0.007.
