### ISSUE TITLE
Only show active accounts in CLI by default, add --show_archived flag

### ISSUE THREAD

**Issue by AbelLykens** [lightninglabs/pool#147]
Would be good to show only active orders in `pool o l` and only active accounts in `pool a l` I think :wink:

**Comment by AbelLykens** [comment]
Okay I should change my upstream to this github one ;).

Still my request is valid for accounts I think :)

**Comment by guggero** [comment]
Changing the title because for orders that's already implemented: https://github.com/lightninglabs/pool/pull/132
