### ISSUE TITLE
Cannot create account

### ISSUE THREAD

**Issue by bota87** [lightninglabs/pool#148]
I'm running litd version 0.3, when I try to create an account I get this error

`$ pool --rpcserver localhost:3004 accounts new --amt 1200000 --expiry_blocks 8064 --conf_target 144`
`[pool] unable to estimate on-chain fees: rpc error: code = Unknown desc = error estimating total on-chain fee: rpc error: code = Unknown desc = insufficient funds available to construct transaction`

I've noticed that my on-chain balance is actualy unconfirmed, maybe is related to the issue? I can't see an option to spend unconfirmed output.

**Comment by Roasbeef** [comment]
Spending unconfirmed change isn't permitted atm.
