### ISSUE TITLE
Can we cancel an ask order after the state changed to "ORDER_PARTIALLY_FILLED"?

### ISSUE THREAD

**Issue by kccheung** [lightninglabs/pool#157]
Using litd v0.3.0-alpha, as title, it seems I cannot cancel an existing ask order after state changed to "ORDER_PARTIALLY_FILLED". As a maker, I would like to update my rate_fixed after an auction round is completed.

**Comment by kccheung** [comment]
Update: I did try once again on my "ORDER_PARTIALLY_FILLED" and cancel is fine. But I got another "ORDER_EXECUTED" order (when `min_units_match` > `units_unfulfilled`) which cannot be cancelled:

```    
{
    "details": {
        "trader_key": "...",
        "rate_fixed": ...,
        "amt": "...",
        "max_batch_fee_rate_sat_per_kw": "...",
        "order_nonce": "......",
        "state": "ORDER_EXECUTED",
        "units": 100,
        "units_unfulfilled": 7,
        "reserved_value_sat": "0",
        "creation_timestamp_ns": "...",
        "events": [
        ],
        "min_units_match": 10
    },
    "lease_duration_blocks": 2016,
    "version": 1
}                       
```

**Comment by Roasbeef** [comment]
When an order has a unit unfulfilled that's below the `min_units_matched`, it's essentially in a terminal state. From the server's PoV it isn't eligible any longer for matching. When an order is in the "executed" state, it's also terminal and is basically already "cancelled".

**Comment by wpaulino** [comment]
Can this issue be closed now @kccheung?

**Comment by kccheung** [comment]
> Can this issue be closed now @kccheung?

Yes. Thanks for @Roasbeef answer.
