### ISSUE TITLE
Absurdly high available_balance in account

### ISSUE THREAD

**Issue by sangaman** [lightninglabs/pool#159]
When I list my accounts to check my balance, I get an absurdly high value for `available_balance`.

```
{
	"accounts": [
		{
			...
			"value": 2046329,
			"available_balance": 18446744073706606460,
			...
		}
	]
}
```

At the moment I have one open order for more than the `value` above that's still unfulfilled, so that also seems wrong and I'm guessing is related. My available balance looks like it's just short of 2^64, so I figure it's doing `value - open_orders` and coming up with a negative number and putting that into an unsigned int field. 

As an aside, I found the name `value` unintuitive and had to read the proto file to understand what it represented, perhaps a name of `balance` would be clearer?

**Comment by Roasbeef** [comment]
See https://github.com/lightninglabs/pool/pull/158

Until that is merged cancelling the order should resolve the available balance value.
