### ISSUE TITLE
docs/faqs: Possible inaccuracy on who pays the on-chain fees

### ISSUE THREAD

**Issue by cryptagoras** [lightninglabs/pool#166]
https://github.com/lightninglabs/pool/blob/master/docs/faq.md#who-pays-the-on-chain-fees
> Who pays the on-chain fees?
> When the channel is opened, the cost of opening the channel is split between the buyer and seller. When the channel is closed, the cost of closing the channel and future UTXO consolidation costs are paid by the buyer.

It was said on slack that this is inaccurate in regards to the closing part. If so and there's an update on the answer, it would be helpful to be clear on who pays the fees in both coop and unilateral closing of the channel.
Also not sure what "future UTXO consolidation costs" refer to.

Thanks

**Comment by Roasbeef** [comment]
Pool doesn't affect channel closing at all. You only pay for channel opening. Correct that it's the seller that may pay for more of the closing fees (since they're the initiator), though this will change as anchor outputs are rolled out more widely.
