### ISSUE TITLE
Confusing log message (formatting): "ACCT: Watching expired account &{{dc 0} c000360da0} for spend"

### ISSUE THREAD

**Issue by C-Otto** [lightninglabs/pool#189]
I see the following log message:

```
ACCT: Watching expired account &{{dc 0} c000360da0} for spend
```

I assume this is a formatting issue, as the account ID usually is shown in a different format.

**Comment by guggero** [comment]
Thanks for the report. This was fixed with #181 and is included in the freshly released version [`v0.3.4-alpha`](https://github.com/lightninglabs/pool/releases/tag/v0.3.4-alpha).
