### ISSUE TITLE
tls.cert missing on windows

### ISSUE THREAD

**Issue by sendbitcoin** [lightninglabs/pool#192]
When i try to create an account using Pool.exe on windows I get this error that the tls.cert can't be found:

_[pool] open C:\Users\xxxxxx\AppData\Local\Pool\mainnet\tls.cert: Das System kann die angegebene Datei nicht finden._

the folder does indeed not have such a file.

**Comment by Ascendzor** [comment]
Same error, on macos. Using testnet though. Have bitcoind and lnd running on testnet.

**Comment by guggero** [comment]
Did you start the pool daemon (`poold.exe` which must run in the background the whole time) first, with the correct settings to connect it to `lnd`?

**Comment by sendbitcoin** [comment]
just tried it and it doesnt make a difference, still same problem.
![2020-12-27 16_05_50-192 168 1 195 - Remotedesktopverbindung](https://user-images.githubusercontent.com/60074674/103179270-7d4fca80-488a-11eb-90d5-1c2256ac4ee3.png)

**Comment by Ascendzor** [comment]
I am not getting an issue anymore.
Unfortunately I don't have the capacity to reproduce this at the moment, but I believe that I was receiving this error when I tried to start `pool` while `LiT` was already running.

**Comment by guggero** [comment]
@sendbitcoin can you please check if there is a `pool.db` file somewhere within `C:\Users\xxxxxx\AppData`? Maybe there is an issue with the data directory on Windows that it somehow expects it to be somewhere else...

**Comment by justinmoon** [comment]
I'm having this same problem on Linux. I'm running the latest release of `litd` on my local machine, but connecting to a `v0.11.0` remote lnd node.

**Comment by justinpobrien** [comment]
Just a heads up that Lightning Terminal is backwards compatible with `lnd` back to version v0.11.1-beta

**Comment by sendbitcoin** [comment]
@guggero pool.db is in C:\Users\xxxxx\AppData\Local\Pool\mainnet\pool.db

I also had lit running but stopping it doesnt seem to make a difference, tls.cert still can't be found.

I currently can't create an account or use pool at all...

Is there any ETA on integrating pool into LIT so I can just use the GUI?

**Comment by guggero** [comment]
Ah, you are running LiT? Then there is no tls.cert created for pool, you need to use the cert from LiT (and the correct port). See https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#example-pool-command

**Comment by halseth** [comment]
Closing per https://github.com/lightninglabs/pool/issues/192#issuecomment-756819080

Feel free to re-open if the linked instructions does not work for you.
