### ISSUE TITLE
transport error while dialing dial tcp connect: connection refused

### ISSUE THREAD

**Issue by pfergi42** [lightninglabs/pool#194]
I am trying to run pool for the first time. I'm already running btcd, lnd and lit.

I had to copy the tls.cert and tls.key file into the /Pool/mainnet directory, but now I try to create an account and get the following error:

```
$ pool accounts new --amt=750000 --expiry_height=1773394

[pool] unable to estimate on-chain fees: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp [::1]:12010: connect: connection refused"
```

**Comment by guggero** [comment]
Are you running the `poold` daemon? You need to start and keep `poold` running in the background. The `pool` binary is just the CLI to interact with the daemon. Same as with `lnd` and `lncli`.

**Comment by pfergi42** [comment]
Thank you, @guggero. I think that was the problem, I had to run poold and put it in the background and it seems to be working now.

I thought pool was bundled as part of litd though, which is and was also running. Is that not actually the case?

**Comment by guggero** [comment]
Ah, you did write you're using LiT. I missed that, sorry.

You are correct, Pool is integrated in LiT and you can only run either/or. But with LiT you need to use a different port and TLS cert, there are examples in the doc: https://github.com/lightninglabs/lightning-terminal/blob/master/doc/config-lnd-remote.md#example-pool-command

**Comment by halseth** [comment]
closing per https://github.com/lightninglabs/pool/issues/194#issuecomment-754285428
