### ISSUE TITLE
REST API  /v1/pool/orders state field when ORDER_SUBMITTED is missing

### ISSUE THREAD

**Issue by mutatrum** [lightninglabs/pool#208]
The state field for newly submitted orders is missing. Through the pool cli, these are shown as ORDER_SUBMITTED.

Secondary: the default for the rest call is active_only = false, for the pool clli, the default is true.

**Comment by mutatrum** [comment]
Scrubbed output of a newly created order, without state field:
```  {
    details: {
      trader_key: 'xxxxx',
      rate_fixed: ####,
      amt: '#####',
      max_batch_fee_rate_sat_per_kw: '####',
      order_nonce: xxxxx',
      units: ##,
      units_unfulfilled: ##,
      reserved_value_sat: '###',
      creation_timestamp_ns: '########',
      min_units_match: #
    },
    lease_duration_blocks: 2016,
    version: 2
  },
```
Cancelled, executed and partially_executed orders do have the `state` field.

**Comment by wpaulino** [comment]
Seems similar to https://github.com/lightningnetwork/lnd/issues/2087, `ORDER_SUBMITTED` is the default value.

**Comment by mutatrum** [comment]
ORDER_SUBMITTED has enum value of 0, I saw that indeed. Looks similar to mentioned issue. I can't easily verify this with the other 0 valued enums.
