### ISSUE TITLE
Feature request: renewing the account when refunding it

### ISSUE THREAD

**Issue by Pantamis** [lightninglabs/pool#218]
I really enjoy Pool, especially with the new UI !

One feature lacking in UI and command line option is to renew the account when I refund it.

Currently we have to do one on-chain transaction to renew the account and one on-chain transaction to refund it, given the current state of the mempool (no full clear since at least 2 months) it starts to be really painfull to not be able to be more efficient in terms of blockspace. Doing both in one single transaction would be great !

From client point of view it looks very simple to implement, maybe it is not from the auctioner point of view.

Thanks !

**Comment by Roasbeef** [comment]
> One feature lacking in UI and command line option is to renew the account when I refund it.

This is already possible from the PoV of the API, but just not yet surfaced on the CLI or the UI.

**Comment by Pantamis** [comment]
I was almost certain it was already implemented ^_^"

I never used the API and I have no idea how to do so I guess I have to wait for it in command line :)

If you have a simple and quick way to use the API just to do it directly for a non-devs like me I am interested. Otherwise too bad that I have to throw more sats than needed at miners in a week haha xD 

Thanks again for the wonderful work !

**Comment by guggero** [comment]
Fixed (at least in the command line) by https://github.com/lightninglabs/pool/pull/305.
