### ISSUE TITLE
LSAT: automatically remove a pending LSAT token if the invoice is expired or the token its is "old enough" 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/pool#221]
As is, it's possible a user attempt to open an account or interact with the system without having any channels open. If they attempt this, then they'll end up with an _pending_ token. In this state, they must either wipe all state or find that token and remove it in order to be able to interact with the system. As Pool gets packaged with more noob friendly packaged UIs, not all of them may have direct access to the command line. As a result, we should either introduce a command to allow them to wipe such state (accessible from the UI), or automatically remove the pending token in a contextual manner.

**Comment by sendbitcoin** [comment]
Sounds like the problem I'm having. https://github.com/lightninglabs/pool/issues/225

I went ahead and renamed the lsat.token and tried again which just made me get "permission denied" and made it create another
![3](https://user-images.githubusercontent.com/60074674/109419342-3b97e900-79cd-11eb-8364-bfe50343e1d2.png)

after that i'm right back to where I started and get the "unable to make new reservation, found existing pending reservation for account" error again only now the account has changed.
