### ISSUE TITLE
Lightning Pool should alert if T0 ranked node: user will not be able to provide liquidity

### ISSUE THREAD

**Issue by snarflakes** [lightninglabs/pool#223]
The default is no purchasing of liquidity from nodes T0. Unfortunately I didn't see that setting is default and went ahead and provided liquidity. A simple alert prior to funding account should read, "T0 node ranking liquidity will unlikely ever be used."
It would also be great if there was a way of closing the account prematurely through the GUI.  I'm an Umbrel user and removing funds should be accessible through GUI (unless i missed how to do that some how). I have read it is possible to withdraw funds still in time-lock by using the CLI.
thanks

**Comment by guggero** [comment]
> T0 node ranking liquidity will unlikely ever be used.

This is not true. There currently might be low demand, yes. But buying channels from T0 nodes can help you become a T1 node so this is still an important market to have.

The UI for Pool is a preview (which it says clearly in the UI) and does not yet have the full functionality the CLI has. I'm not sure how you can use the CLI with Umbrel, but closing an account is documented here: https://github.com/lightninglabs/pool/blob/master/docs/accounts.md#closing-an-account

**Comment by snarflakes** [comment]
okay i will leave my way under market priced liquidity and see if there is any action that comes along in the next couple of months.  I can be the canary in the goldmine.  But still, maybe a red highlight on a T0 node? instead of making it by default completely not visible? that way users at least know T0 funds exists?

**Comment by Roasbeef** [comment]
We have a new extension to the RPC planned to let users query the total interest which includes a break down of t0 vs t1.

**Comment by snarflakes** [comment]
Suweet!
