### ISSUE TITLE
Fix account documentation

### ISSUE THREAD

**Issue by gked** [lightninglabs/pool#226]
The [documentation](https://pool.lightning.engineering/accounts#closing-an-account), describing account closure is incorrect. The example omits required option  `--sat_per_vbyte.`
![image](https://user-images.githubusercontent.com/12704474/109450683-5e8fc080-7a00-11eb-8cf7-3e8df5307959.png)

Please update your example from
`*pool accounts close --trader_key=0288096be9917f8ebdfc6eb2701635fe658f4eae1e0274dcce41418b3fb5145732`

to

` pool accounts close --trader_key=0288096be9917f8ebdfc6eb2701635fe658f4eae1e0274dcce41418b3fb5145732 --sat_per_vbyte 0`

**Comment by gked** [comment]
@guggero looks like you are open to get help on this. I can create a pull request.

**Comment by Roasbeef** [comment]
Fixed by #229
