### ISSUE TITLE
Unable to fund account in pool ui

### ISSUE THREAD

**Issue by MR-Neto** [lightninglabs/pool#227]
I am getting this error of `insufficient_balance`, even tough I have on-chain balance. Do I need to have off-chain balance in order to fund my pool account? 

![image](https://user-images.githubusercontent.com/45563365/109623328-52f5e400-7b3d-11eb-80d4-931cf5a9bb08.png)

**Comment by guggero** [comment]
Yes, you need to be able to pay a one-time payment of 1k sats to obtain the LSAT token, see https://github.com/lightninglabs/lightning-terminal/pull/190.

This obviously isn't optimal for onboarding new users. But we're working on that with the concept of sidecar channels which will work without the recipient needing to have any channels at all.

I'm closing the issue as this is a known restriction of the early alpha/preview.
