### ISSUE TITLE
Adding funds to open account throws error in LiT

### ISSUE THREAD

**Issue by daldwinc** [lightninglabs/pool#234]
Attempting to add more funds to an "open" account produces an error in LiT. The account:

![image](https://user-images.githubusercontent.com/36732642/111080358-825d0700-84d4-11eb-849a-6913706716fc.png)

Clicking "Fund Account" and then "Confirm" throws an error. 

![image](https://user-images.githubusercontent.com/36732642/111080450-e8e22500-84d4-11eb-9b98-566a4015314d.png)

![image](https://user-images.githubusercontent.com/36732642/111080465-fdbeb880-84d4-11eb-9c7a-e11e2d341a2d.png)

**To reproduce**

I can reproduce at will by attempting to add more funds. I have not tried closing the account and reopening one.

**System information**

I am using Pool through Lightning Terminal.

I used this script to install on LiT on raspiblitz:

https://github.com/rootzoll/raspiblitz/issues/1993

The version installed by the script is 0.4.1-alpha.

Brave Browser on macOS to work with LiT, but LiT is running on a Pi 4 Model B Quad Core 64 Bit WiFi Bluetooth (8GB).

I'll post logs once I find them...

**Comment by guggero** [comment]
That account was closed with transaction `d60573fd488b69c0ac757260294f37b33d8732e18c0a68bbf5c40c9f012796cc` in December. Can you post some of the LiT logs to see why this isn't picked up by LiT?
Can be that the chain rescan just takes a while to complete and then Pool/LiT will mark it as closed correctly (this sort of thing takes especially long on hardwire like the RaspiBlitz and more so after a long time offline).

**Comment by daldwinc** [comment]
Hi @guggero - I apologize but that night my impatience got the better of me. I closed the account and re-opened it with a larger amount which seems to work. 

I'll keep an eye on it, but for now I think this can be closed.
