### ISSUE TITLE
Command line args are not correctly parsed

### ISSUE THREAD

**Issue by rnitta** [lightninglabs/pool#236]
**Expected behavior**
```
$ poold --lnd.tlscertpath /some_dir/.lnd/tls.cert
```

The command above is acceptable.
ref: https://pool.lightning.engineering/install#running-poold

**Actual behavior**

```
[hoge@ip-10-0-0-39 ~]$ poold --lnd.tlscertpath /some_dir/.lnd/tls.cert
unknown flag `lnd.tlscertpath'
unknown flag `lnd.tlscertpath'
```

`lnd.tlscertpath` option is not accepted.

then I tried:

```
[hoge@ip-10-0-0-39 ~]$ poold --tlscertpath /some_dir/.lnd/tls.cert
2021-03-17 13:50:43.144 [INF] LLMD: Version: 0.4.1-alpha commit=
2021-03-17 13:50:43.144 [INF] LNDC: Creating lnd connection to localhost:10009
unable to start server: open /home/hoge/.lnd/tls.cert: no such file or directory
```

The cert file location seems to be passed,  but poold may not use it.

**To reproduce**

download 0.4.1-alpha arm64binary and boot it with the command above.

**System information**

Not using lightening terminal. I use it as standalone app.

LND 0.11.1-beta

OS: amazon linux
CPU: AWS Graviton2
binary: ARM64 0.4.1-alpha

**Comment by guggero** [comment]
The correct flag for setting lnd's TLS certificate path is `--lnd.tlspath` not `--lnd.tlscertpath` as is pointed out in the docs you linked and also when using `poold --help`.
