### ISSUE TITLE
orders: allow matching with special requirements (anchor commitments etc.)

### ISSUE THREAD

**Issue by cryptagoras** [lightninglabs/pool#240]
As a seller/maker one issue that varies the experience of selling a channel lease is if the buyer will stay online or for whatever reason making me force close the channel which usually results in non-trivial economic damage.

Anchor channels provide a serious improvement on these cases, so as a seller I would like to be able to specify that I'm selling only anchor channel leases.

This will provide a greater peace of mind and allow me to provide better offers without having to account for potentially costly force-closings.

(I know this is probably too niche and hopefully anchors will get adopted faster enough, but maybe keep it in mind :clinking_glasses:  )

**Comment by Roasbeef** [comment]
Def, this is in the works as an explicit order type. Needs a small change to lnd that makes channel types _explicit_: https://github.com/lightningnetwork/lnd/pull/5071

**Comment by guggero** [comment]
Going through the older issues, I noticed this was fixed by https://github.com/lightninglabs/pool/pull/300.
