### ISSUE TITLE
Bad signature on v0.4.1 release manifest

### ISSUE THREAD

**Issue by sipsorcery** [lightninglabs/pool#248]
````
~$ sha256sum -c --ignore-missing manifest-v0.4.1-alpha.txt
lightning-terminal-linux-amd64-v0.4.1-alpha.tar.gz: OK
````

````
~$ gpg --verify manifest-v0.4.1-alpha.txt.sig
gpg: assuming signed data in 'manifest-v0.4.1-alpha.txt'
gpg: Signature made Thu Jan 14 03:35:05 2021 UTC
gpg:                using RSA key 60A1FA7DA5BFF08BDCBBE7903BBD59E99B280306
gpg: BAD signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [unknown]
````

**Comment by wpaulino** [comment]
I was able to verify the signature, see my results here: https://privatebin.net/?7359237f4a0286eb#zDkEGJoiWMaMyFqgideVWdsY8WBKBayZZsvmGk5uWwD

Did you get the manifest/signature files mixed up somehow?

> ~$ sha256sum -c --ignore-missing manifest-v0.4.1-alpha.txt
lightning-terminal-linux-amd64-v0.4.1-alpha.tar.gz: OK

`lightning-terminal-linux-amd64-v0.4.1-alpha.tar.gz` is for https://github.com/lightninglabs/lightning-terminal.

**Comment by sipsorcery** [comment]
> Did you get the manifest/signature files mixed up somehow?

Yes that's exactly what I did. I thought I'd doubled checked everything but I didn't even notice the duplicate manifest file names.

Thanks for confirming. I was able to verify the signature when using the correct manifest:

````
~$ gpg --verify manifest-v0.4.1-alpha.txt.sig
gpg: assuming signed data in 'manifest-v0.4.1-alpha.txt'
gpg: Signature made Thu Jan 14 03:35:05 2021 UTC
gpg:                using RSA key 60A1FA7DA5BFF08BDCBBE7903BBD59E99B280306
gpg: Good signature from "Olaoluwa Osuntokun <laolu32@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: E4D8 5299 674B 2D31 FAA1  892E 372C BD76 33C6 1696
     Subkey fingerprint: 60A1 FA7D A5BF F08B DCBB  E790 3BBD 59E9 9B28 0306
````
