### ISSUE TITLE
Can't create mainnet account with Lightning Terminal UI

### ISSUE THREAD

**Issue by sipsorcery** [lightninglabs/pool#249]
**Expected behavior**

A new mainet pool account gets created using the Lightning Terminal UI.

**Actual behavior**

Account creation fails with error `UNABLE TO CREATE THE ACCOUNT no_route`.

![pool_noroute](https://user-images.githubusercontent.com/197660/116418204-d24d1e80-a833-11eb-9c52-ad1c8db0a338.png)

**To reproduce**

The parameters I used when attempting to create the new account:

Amount: 3,000,000
Expires In: 12,960
Confirmation Target: 6

The `no_route` error would seem to indicate the lighting invoice for the Pool account creation can't be paid? My `lnd` node has a channel open to a `LOOP` node `021c97a90a411ff2b10dc2a8e32de2f29d2fa49d41bfbb52bd416e460db0747d0d` with a local capacity of `7,999,817`.

**System information**

**Are you using Lightning Pool as a standalone application or as part of Lightning Terminal?** Lightning Terminal.

**If you are using Lightning Pool as part of Lightning Terminal, did you install that using Umbrel?** No.

**How are you interacting with Pool? Through the command line interface or the Lightning Terminal UI?** Lightning Terminal UI

**What version of Lightning Pool are you using, where did you get it (website, self-compiled, etc)**

`Lighting Terminal release v0.4.1-alpha`

````
~/lightning-terminal-linux-amd64-v0.4.1-alpha$ ./pool --version
pool version 0.4.4-alpha commit=v0.4.4-alpha
````

**What type of machine are you observing the error on (OS/CPU and disk type)?**

Azure Virtual Machine.

**What is your operating system and its version?**

````
azureuser@btcazure:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic
azureuser@btcazure:~$ uname -a
Linux btcazure 5.4.0-104
````

**Additional Info**

Possibly related to #225 but the errors described there are different. I was able to create a new Pool account using the same installed components on `testnet`.

**This is normally the contents of a `pool.log` file. Raw text or a link to a pastebin type site are preferred.**

Relevant section of the `litd` terminal output:

````
2021-04-28 14:11:32.423 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/ListAccounts
2021-04-28 14:11:32.601 [INF] LITD: Handling gRPC web request: /lnrpc.Lightning/GetInfo
2021-04-28 14:11:32.638 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/ListOrders
2021-04-28 14:11:32.830 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/Leases
2021-04-28 14:11:37.068 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/QuoteAccount
2021-04-28 14:11:38.705 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/InitAccount
2021-04-28 14:11:38.878 [INF] ACCT: Estimated total chain fee of 0.00000224 BTC for new account with value=0.03 BTC, conf_target=6
2021-04-28 14:11:39.050 [ERR] AUCT: [/poolrpc.ChannelAuctioneer/ReserveAccount]: rpc error: code = Internal desc = payment required
2021-04-28 14:11:39.050 [INF] LSAT: Payment of LSAT token is required, paying invoice
2021-04-28 14:11:39.086 [WRN] LNDC: Payment 6b0f01a84a704b0e7bd3a1099b2d4a8a40e8de7ad27a295aeeb334a84614e5b7 failed: no_route
2021-04-28 14:12:32.041 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/BatchSnapshots
2021-04-28 14:12:32.239 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/NextBatchInfo
2021-04-28 14:12:32.417 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/ListAccounts
2021-04-28 14:12:32.645 [INF] LITD: Handling gRPC web request: /lnrpc.Lightning/GetInfo
2021-04-28 14:12:32.703 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/ListOrders
2021-04-28 14:12:32.892 [INF] LITD: Handling gRPC web request: /poolrpc.Trader/Leases
````

**Comment by guggero** [comment]
According to the log the 1k LSAT payment failed. Though I don't see any apparent reason. The target node is not the LOOP node, but another one. It has enough inbound liquidity though. Can you remove the `lsat.token.pending` file and try again please?

**Comment by sipsorcery** [comment]
Just deleted the token and retired another couple of times but same error (I had deleted and retried probably a dozen times previously).

**Comment by sipsorcery** [comment]
Can the LOOP node route payments to the node for the Pool invoice payment? Is there anyway I can check whether I can reach the Pool node?

**Comment by guggero** [comment]
Hmm, there is a channel between the Loop node and the Pool node though it was depleted. I did some shuffling around, can you try again please?

**Comment by sipsorcery** [comment]
Still same error.

Don't know if this is relevant at all but just in case:

````
azureuser@btcazure:~/lightning-terminal-linux-amd64-v0.4.1-alpha$ ./pool --rpcserver swap.lightning.today:11010 --tlscertpath
swap.cert accounts new 3000000
[pool] unable to estimate on-chain fees: rpc error: code = Unimplemented desc = Not Found: HTTP status code 404; transport: received the unexpected content-type "text/plain; charset=utf-8"
azureuser@btcazure:~/lightning-terminal-linux-amd64-v0.4.1-alpha$ ./pool --rpcserver pool.lightning.finance:12010 --tlscertpath pool.cert accounts new 3000000
[pool] unable to estimate on-chain fees: rpc error: code = Internal desc = payment required
````

**Comment by guggero** [comment]
No, don't connect to the Loop backend! That will give you the wrong LSAT but you still pay for it.

**Comment by guggero** [comment]
Ah, well, the `--rpcserver` flag in your case is what server the `pool` CLI talks with. So you'll never get a positive response from both of these servers as they have another gRPC interface than your `poold`.

**Comment by guggero** [comment]
Okay, something's still wrong with the inbound liquidity on our side. Going to look into opening more channels.

**Comment by guggero** [comment]
In the meantime you can contact me on Slack and I'll create an LSAT for you so you can continue with opening your account.

**Comment by guggero** [comment]
Chatted with @sipsorcery on Slack and were able to find the problem. Inbound liquidity to the pool server is sufficient but @sipsorcery's `lnd` node didn't have its graph fully synced yet.
