### ISSUE TITLE
Unable to fetch latest batch

### ISSUE THREAD

**Issue by rek79** [lightninglabs/pool#274]
I have Lightning Pool up and running with account funded successfully.  I was also able to create an ask order. However, the order is never filled even though the premium is within market range. Periodic errors received through web interface are shown below.  Are those errors normal?  Is it possible that the order is not being filled due to Node Tier=T0 and offered liquidity is only 400,000 sats?

![image](https://user-images.githubusercontent.com/9994060/127230648-4ad519d2-0024-4c24-bdac-d801989290b7.png)

![image](https://user-images.githubusercontent.com/9994060/127230671-e27a2496-7019-4f2d-9799-1edc46c24d47.png)

LIT logs:

![image](https://user-images.githubusercontent.com/9994060/127230725-5a34cafa-b082-4606-a0d1-e0859ce51ff1.png)

Order gets filled.

Order does not get filled.

Hardware: Odroid HC2
Software: Raspiblitz v1.7 running on Armbian Buster OS

**Comment by guggero** [comment]
The "context deadline exceeded" is golang's way of saying "request timed out". It sounds like your network connection is slow at times. Are you running Tor only? This could also explain why your order doesn't get matched, you need to be able to connect out to the matched party within a given time or your match will be canceled.

**Comment by rek79** [comment]
Yes, connection is Tor only.  Are there any settings I can tweak to allow Tor operation?

**Comment by rek79** [comment]
@guggero I wasn't sure from your previous response if it's possible to run Tor only with Lightning Pool.  Will I need to configure my node to run over clearnet in order to fill orders?

**Comment by guggero** [comment]
Are you running all connections through Tor? For example with something like Torify? Because the call that is timing out should normally go through clearnet, even if lnd is using Tor only.

You can use a Tor only node with Lightning Pool. But it'll mean that your node needs to connect out to all takers and if that times out the order won't be filled. Try restarting and updating your Tor proxy to make sure you get fresh circuits if you have general connection issues.

**Comment by rek79** [comment]
I restarted about a week ago and that seemed to have gotten rid of the error messages originally reported.  However, still no takers.  I'm running Raspiblitz with Tor only config.  Bitcoind config file has onlynet = onion.  Here is the full config file:

bitcoind config:
![image](https://user-images.githubusercontent.com/9994060/128035892-921ecd8e-e249-4769-a6dd-d7584ffbcb70.png)

lnd config:
![image](https://user-images.githubusercontent.com/9994060/128035423-1a0bf818-8c2d-4b16-8c5e-54afbed76490.png)

**Comment by guggero** [comment]
There aren't a lot of batches going on yet. And if your node is T0 people need to opt-in to receive liquidity from your node. So this might take a good while. Also there currently are way more asks than bids.

**Comment by rek79** [comment]
Okay, that makes sense.  Thanks.  I'll read up on ways to increase the tier of my node.
