### ISSUE TITLE
Account in PENDING_STATE state

### ISSUE THREAD

**Issue by villastrangiato** [lightninglabs/pool#296]
My account has been in `PENDING_STATE` for several hours and the `latest_txid` apparently hasn't been broadcasted. 

That txid is about a lease for a channel that hasn't been opened (yet?) and whose `purchased` field value is `false`

Also, recently deposited funds are missing.

```
{
	"accounts": [
		{
			"trader_key": "03ec72c6c0ab9aa6d63e76fe1d650f0b2518395b10cef6b2381b3d93a41601a600",
			"outpoint": "3cf6f7569097bfc0a53992aee575726d2536eaddf9955581f8d7af90f4a5c080:1",
			"value": 1001008,
			"available_balance": 421373,
			"expiration_height": 708527,
			"state": "PENDING_BATCH",
			"latest_txid": "3cf6f7569097bfc0a53992aee575726d2536eaddf9955581f8d7af90f4a5c080"
		}
	]
}
```

```
{
	"leases": [
		{
			"channel_point": "3cf6f7569097bfc0a53992aee575726d2536eaddf9955581f8d7af90f4a5c080:2",
			"channel_amt_sat": 1000000,
			"channel_duration_blocks": 2016,
			"channel_lease_expiry": 0,
			"channel_node_key": "03789e3087822b0e5d94c6e5f452131a174d4da580c6a355d9434be6e8f7469438",
			"channel_node_tier": "TIER_0",
			"premium_sat": 2175,
			"clearing_rate_price": 1079,
			"order_fixed_rate": 992,
			"execution_fee_sat": 1001,
			"chain_fee_sat": 166,
			"order_nonce": "6ba4dfe6799e77624c82bd8ec874ce2eff6130cf7096f282437e38ab1e112048",
			"matched_order_nonce": "a384d0f2bf15a97ff1f644cc01dfe8117dff5782cce5f3cc10a7c16cce3816a9",
			"purchased": false,
			"self_chan_balance": 0,
			"sidecar_channel": false
		}
	],
	"total_amt_earned_sat": 2175,
	"total_amt_paid_sat": 1167
}
```

pool version 0.5.1-alpha commit=v0.5.1-alpha
lncli version 0.13.3-beta commit=v0.13.3-beta

thanks!

**Comment by Roasbeef** [comment]
We're you a part of a recent batch? The batch execution transaction just may not have been confirmed yet.

**Comment by villastrangiato** [comment]
> The account shows as `STATE_OPEN` on the server with the value of 2'200'000 sats. So it seems like a batch didn't go through with your orders but your account state got out of sync. Did you try restarting the poold node?


yes, I tried yesterday: I restarted both poold and lnd.
if there's anything I can try or information I could provide, please let me know.

thanks for investigating so far!
