### ISSUE TITLE
Sidecar registration issue leading to additional poold failures

### ISSUE THREAD

**Issue by kornpow** [lightninglabs/pool#338]
*Issue*
We are running into situations where "write" API calls begin to hang indefinitely/fail.
So far we have noticed this on the functions `create sidecar` and `cancel sidecar` functions. However, things like quoting orders, and viewing previous batches still works.

I cannot determine whether the issue occurs, and a user hits it, and then we notice the issue,

OR

the user creates an order, and something bad happens during their registration process, and in the process, it breaks our Pool instance.

**Expected behavior**

The user should be able to register a sidecar, and if something goes wrong, things should cleanup smoothly, and not break our Poold instance.

**Potentially related error logs: **
This error was being put into our logs, for a variety of different sidecar tickets, relatively frequently, around every few seconds.
```
2022-01-20 19:24:01.276 [ERR] AUCT: [/poolrpc.HashMail/RecvStream]: rpc error: code = Unknown desc = stream not found
2022-01-20 19:24:01.276 [ERR] POOL: unable to recv cipher box msg: rpc error: code = Unknown desc = stream not found
```

After restarting our poold instance the above errors were not spammed in our logs anymore.

However I noticed this message in our logs, after restart
```
2022-01-20 20:57:52.345 [ERR] POOL: unable to transition state: unhandled provider state transition ticket=10c836837ba5021a, state=offered
2022-01-20 20:57:52.354 [ERR] POOL: unable to transition state: unhandled provider state transition ticket=1108335ff3420a29, state=offered
2022-01-20 20:57:52.376 [ERR] POOL: unable to transition state: unhandled provider state transition ticket=2b6b384a17f3f213, state=offered
2022-01-20 20:57:52.384 [ERR] POOL: unable to transition state: unhandled provider state transition ticket=310358470b8866f1, state=offered
```

**Comment by dstadulis** [comment]
@positiveblue 
seems like error is occuring here
https://github.com/lightninglabs/pool/blob/bc8537add98ee922a1eb95b39bfe4b0a8680f209/auto_sidecar.go#L822-L868
https://github.com/lightninglabs/pool/blob/bc8537add98ee922a1eb95b39bfe4b0a8680f209/auto_sidecar.go#L866

**Comment by dstadulis** [comment]
@kornpow Are you still experiencing this? It's possible this issue is due to improper handling of how poold handles the auctioneer server being down.

**Comment by kornpow** [comment]
Its not something we hit all the time, usually it resolves itself with a restart of `poold`

Restarting Pool isnt the end of the world, if we can detect the problem is happening quickly.

**Comment by dstadulis** [comment]
@kornpow 
We've tracked down the route cause.  There's a long-term fix being planned but in the mean time, wanted to loop you in on how we recommend Voltage's dev-ops team handle the issue.

**Background:**
When negotiating a sidecar channel, two different processes run which interact with the auctioneer.  The first handles normal auction actions and the second process is handles sidecar creation (auto negotiation).  During this second process data streams are not persisted so if a client or the server shuts down, the sidecar registration will fail to register properly.

**short-term fix/kludge/bodge**
If the server or client go offline during sidecar registration, Voltage automating a restart of the pool client will ensure that sidecar registration operates smoothly.

Taproot upgrades to Pool are our focus rn.

**Comment by kornpow** [comment]
A part of this problem is detecting that there is an issue in the first place, so we can trigger a restart of the server.

Do you have any recommendations of API calls we could do, which would trigger the hanging error? We likely wouldnt want to be creating or cancelling a sidecar, to test?

or maybe that is the way. Create and then cancel the sidecar once every X amount of time, and warn our team if it fails/ timesout.

**Comment by Roasbeef** [comment]
Recapping a conversatin here:
* Right now the retransmission logic only executes when _one_ side restarts. 
* This means the case of the server restarting and dropping any possibly queued messages isn't handled.
* If one side restarts, retransmission happens and both sides are synced up. 
* We need to detect a restart via [a failed read](https://github.com/lightninglabs/pool/blob/master/auto_sidecar.go#L312), re-create the mailbox, then restart that goroutine.
    * A restart of the goroutine will trigger all the normal retransmission logic
