### ISSUE TITLE
Lease created with wrong expire height

### ISSUE THREAD

**Issue by vegardengen** [lightninglabs/pool#346]
I have an order, created with pool v0.5.4-alpha, in the 12096 block market.

The order was successfully matched, channel created and operational - but it's channel_lease_expiry is set as 1462191 !

**Expected behavior**

Channel-lease expiry should be creation height plus 12096 blocks.

**Actual behavior**

Channel-lease expiry is way in the future.

**To reproduce**

Not easily reproducable as I don't have any details to know why this happened.

**System information**

Pool v0.5.4-alpha as part of LiT 0.6.4-alpha (at time of channel creation)
 
Due to a known bug for order creation, the order was created manually with pool command this time.

Details (identifying data removed, can be had upon request):

               {
                        "channel_point": "**************:0",
                        "channel_amt_sat": 3000000,
                        "channel_duration_blocks": 12096,
                        "channel_lease_expiry": 1462191,
                        "channel_node_key": "************************",
                        "channel_node_tier": "TIER_1",
                        "premium_sat": 25474,
                        "clearing_rate_price": 702,
                        "order_fixed_rate": 578,
                        "execution_fee_sat": 3001,
                        "chain_fee_sat": 165,
                        "order_nonce": "********",
                        "matched_order_nonce": "*******",
                        "purchased": false,
                        "self_chan_balance": 0,
                        "sidecar_channel": false
                }

**Comment by Roasbeef** [comment]
We think this might just be a bug in the RPC server itself. 

Can you give a similarly redacted output for the `lncli listchannels` output related to that outpoint?

**Comment by vegardengen** [comment]
`     "channel_point": "****************:0",
            "chan_id": "*************",
            "capacity": "3000000",
            "local_balance": "2997914",
            "remote_balance": "0",
            "commit_fee": "1756",
            "commit_weight": "772",
            "fee_per_kw": "1269",
            "unsettled_balance": "0",
            "total_satoshis_sent": "0",
            "total_satoshis_received": "0",
            "num_updates": "70",
            "pending_htlcs": [
            ],
            "csv_delay": 360,
            "private": false,
            "initiator": true,
            "chan_status_flags": "ChanStatusDefault",
            "local_chan_reserve_sat": "30000",
            "remote_chan_reserve_sat": "30000",
            "static_remote_key": false,
            "commitment_type": "SCRIPT_ENFORCED_LEASE",
            "lifetime": "1070022",
            "uptime": "1067917",
            "close_address": "",
            "push_amount_sat": "0",
            "thaw_height": 737140,
            "local_constraints": {
                "csv_delay": 360,
                "chan_reserve_sat": "30000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "2970000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            },
            "remote_constraints": {
                "csv_delay": 360,
                "chan_reserve_sat": "30000",
                "dust_limit_sat": "354",
                "max_pending_amt_msat": "2970000000",
                "min_htlc_msat": "1",
                "max_accepted_htlcs": 483
            }
        },
`

**Comment by guggero** [comment]
Thaw height used to be relative, is now absolute (with channel type `SCRIPT_ENFORCED_LEASE`): https://github.com/lightninglabs/pool/blob/master/rpcserver.go#L1962

**Comment by Roasbeef** [comment]
Ok yeah this confirms that the line above wasn't updated to account for the new channel type. So this is mainly a "cosmetic" bug and the lease was created with the proper duration.
