### ISSUE TITLE
LSAT bought without user intervention

### ISSUE THREAD

**Issue by EricYHF** [lightninglabs/pool#356]
My node crashed, after it recovered POOL payed 1000 sats for a LSAT out of the blue

**Expected behavior**

Not to have pool send my satoshis away...

Running myNode v0.2.52, pool v-.5.4-alpha, on a Debian VM

Apr 11 21:09:29 myNode-VM pool[14022]: 2022-04-11 21:09:29.902 [INF] RPCS: Received new block notification: height=731448
Apr 11 21:11:45 myNode-VM pool[14022]: 2022-04-11 21:11:45.532 [ERR] AUCT: [/poolrpc.ChannelAuctioneer/MarketInfo]: rpc error: code = Internal desc = payment 
Apr 11 21:11:45 myNode-VM pool[14022]: 2022-04-11 21:11:45.534 [INF] LSAT: Payment of LSAT token is required, paying invoice
Apr 11 21:11:47 myNode-VM pool[14022]: 2022-04-11 21:11:47.867 [INF] LNDC: Payment 1b770fb14e886a656b84b2bd30537cbe77249b95e660ef6f6f541650b000e1e7 completed
Apr 11 21:15:17 myNode-VM pool[14022]: 2022-04-11 21:15:17.340 [INF] RPCS: Received new block notification: height=731449

Jordi on LL Telegram looked into this and stated:
"it really looks like some script or someone from the terminal called pool getinfo and that triggered the one time 1000 sat payment because you did not use it before (LSAT token is not needed when registering a token)"

**Comment by guggero** [comment]
It looks like we forgot to add the `MarketInfo` RPC to the LSAT whitelist so it can be called without needing a token. Sorry about that, we'll fix it asap. Hit me up on Slack for a refund.

**Comment by guggero** [comment]
The fix will be deployed to the server in the next maintenance window. User was reimbursed for the LSAT.
