### ISSUE TITLE
Lost Pool history after reinstalling

### ISSUE THREAD

**Issue by ForTheEndOfTheState** [lightninglabs/pool#389]
I logged into the Pool and saw the funds in the account = 140,314 sats.

So, I went to add more funds Founds Amount **1,000,000** , but when I press 'confirm' the message **“Unable to deposit found” rpc error = Unknow dest unsupported 5120c95c... "** is shown as error.

I was on onchain funds when I tried.

I reinstalled **Lightning Terminal** and after that, I was able to add funds to the account, but in a new account.

How can I see the transaction history and get the funds back 140,314 sats that are in the old account?
 
I'm using the Pool through Umbrel!

![2022-09-13 21 50 12](https://user-images.githubusercontent.com/113484330/190034540-310016c1-bb5b-4d8d-89ca-25ce8f8000be.jpg)

**Comment by guggero** [comment]
Uninstalling the app means deleting its data. So the transaction history can't be restored at this time (see https://github.com/lightninglabs/pool/issues/381).
To get the funds back, you need to run account recovery. There's a step-by-step description here: https://github.com/lightninglabs/lightning-terminal/issues/372#issuecomment-1136042794

**Comment by iksolon** [comment]
<img width="175" alt="Screen Shot 2022-09-14 at 09 33 29" src="https://user-images.githubusercontent.com/107311059/190154536-89f04d14-9320-45bf-9c6c-705a406a983e.png">


I opened a new issue #417, but I think it is the same problem.

**Comment by ForTheEndOfTheState** [comment]
When I run the command:
pool --rpcserver=localhost:8443 --tls cert path=~/.lit/tls.cert --macaroon path=~/.pool/mainnet/pool.macaroon account list
It just shows me the new open channel.
I believe that if I run this command, I will close the pool I opened. The problem started when I tried to put funds in the pool and got the same error: https://github.com/lightninglabs/pool/issues/389#issuecomment-1246697530
My old account, I don't know how have access.


```
{
	"accounts": [
		{
			"trader_key": “031ad04a8f3 edited b6a8eb681b760c",
			"outpoint": “79c2597e796 edited 5ddeb55d0a8a3 edited 8c2f6b6f6da0604:1",
			"value": 2000000,
			"available_balance": 1440,
			"expiration_height": 766961,
			"state": "OPEN",
			"latest_txid": “79c2597e7962b28c edited cac5ddeb55d0a8a3214 edited b6f6da0604"
		}
```

**Comment by guggero** [comment]
You need to delete the `pool.db` file first, then run the account recovery. That will recover **both** accounts, the new one and the old. But you cannot run the account recovery as long as you already have an existing Pool database with an account in it.
