### ISSUE TITLE
pool: daemon hangs for certain classes of unclean shutdown 

### ISSUE THREAD

**Issue by Roasbeef** [lightninglabs/pool#42]
I've observed a few instances of the daemon hanging and refusing to shutdown with a CTRL-C. The way I've mostly reliably reproduced it so far is to sever the connection with the server somehow (either using something like iptables, or restart the server all together). When I looked into this issue last, it seemed to be the case that the handshake logic was stuck, and wouldn't progress, nor shutdown.

**Comment by halseth** [comment]
@guggero This is fixed now, right?

**Comment by guggero** [comment]
I think so, yes. Can always reopen if it happens again.
