### ISSUE TITLE
broken debug string

### ISSUE THREAD

**Issue by C-Otto** [lightninglabs/pool#425]
I see the following log message, where "%v" should have been replaced by some more helpful string.

```
[ERR] RPCS: Unknown server error: %v server sent unexpected error
```

poold version 0.6.1-beta commit=v0.6.0-beta-18-g5e95640ec64759681b49c0f49adf52abd06cb45c-dirty

**Comment by positiveblue** [comment]
Thanks for catching this @C-Otto 

The information about the received error is in another log entry that starts with `Server connection error received: ...`

In this specific case `%v` should have been substituted by `server sent unexpected error`, we were using `Error()` instead of `Errorf()`
