### ISSUE TITLE
Ask order ERROR

### ISSUE THREAD

**Issue by barbaloka** [lightninglabs/pool#433]
Hi, I'm not a developer.
When trying to place an ask order in the pool, this error is returning, as shown in the attached image. What should I do? I use myNode.
I wait and thank you
![Captura de Tela 2023-01-13 às 12 51 13](https://user-images.githubusercontent.com/122633031/212382004-3e41bf02-bb18-4e8d-b55c-a62ee4609525.png)

**Comment by positiveblue** [comment]
Hi @barbaloka it looks like pool is not able to parse some of the uris of your node. Do you have any custom uris for your node? 

You can get them from the cli using `lncli getinfo`

**Comment by barbaloka** [comment]
Thanks for the quick feedback.
I believe I don't have any, I ran the suggested command and it returned only the 2, clearnet and TOR.
I wait.

**Comment by positiveblue** [comment]
For both uris the format should be:

```
{nodeID}@{ip}:{port} # for the clear net one
{nodeID}@{addr}.onion:{port} # for the tor one
```

What are the ports for those uris?

**Comment by barbaloka** [comment]
Clear net port : 87654
onion port: 9735

**Comment by positiveblue** [comment]
The go resolver won't be able to parse any port higher than `65535`. 

The way to fix this is exposing your LND node through a smaller port.

**Comment by barbaloka** [comment]
Right, and how can I change it?
Are there any security implications?

**Comment by positiveblue** [comment]
No security implications per se but you will need to ensure that the new port has the same security constraints that you set to that other port: same firewall configuration, reverse proxied if needed, etc

**Comment by positiveblue** [comment]
The underlying issue has been identified + possible solutions have been provided. I will close the this issue.
