### ISSUE TITLE
Can't add funds to existing pool account

### ISSUE THREAD

**Issue by pfergi42** [lightninglabs/pool#443]
I'm trying to add funds to my pool account.

Funds to be added.

I get this error:
![err](https://user-images.githubusercontent.com/4021240/221723533-41c4b592-a5cf-4454-9c70-cd5fe7a2fdb9.png)

Happens every time.

I'm running LND 0.15.5 and Pool 0.6.1

Part of Lightning Terminal Web

No

Terminal UI 

0.6.1

n/a

n/a

**Comment by positiveblue** [comment]
You need to update your [lightning-terminal](https://github.com/lightninglabs/lightning-terminal/releases/tag/v0.8.6-alpha)

**Comment by positiveblue** [comment]
I see that the problem has been already solved. Feel free to reopen if not.
