### ISSUE TITLE
Logs missing crucial information

### ISSUE THREAD

**Issue by C-Otto** [lightninglabs/pool#458]
I'm using pool 0.6.4-beta. When I start poold via systemd, it fails after a second or so. The logs don't indicate anything useful:

```
2023-06-17 10:35:17.439 [INF] RPCS: Starting trader server
2023-06-17 10:35:17.522 [INF] RPCS: Connected to lnd node c-otto.de with pubkey 027ce055380348d7812d2ae7745701c9f93e70c1adeb2657f053f91df4f2843c71
2023-06-17 10:35:17.980 [INF] AUCT: Shutting down auctioneer client
```

However, when I start poold manually, I get this:

```
unable to start server: unable to start account manager: unable to resume account xxx: rpc error: code = Unknown desc = transaction rejected: output already spent
```

Please consider showing important information like this in the logs.

**Comment by guggero** [comment]
@C-Otto thanks for the report. Do you know if `systemd` captures `stderr`? Because if there is an error _before_ `poold` has set up the logging system (e.g. configuration file cannot be parsed), then we now log to `stderr` (see https://github.com/lightninglabs/pool/pull/459) instead of `stdout`.

**Comment by C-Otto** [comment]
I'm pretty sure systemctl is able to capture stderr, but in this case (copied over from my lnd setup) I disabled capturing output as I already have the log file. If errors like this aren't supposed to end up in the log file, I might have to tweak my setup. Otherwise, I'd like this message to appear in the log file (additionally to stderr).

**Comment by C-Otto** [comment]
Sounds good to me! It's not too hard to check stdout/stderr, especially if the logs are empty.
