### ISSUE TITLE
Account open allows for undercutting the `lnd` anchor reserve requirement.

### ISSUE THREAD

**Issue by hieblmi** [lightninglabs/pool#461]
When opening a pool account the funding amount doesn't seem to be reconciled with the anchor reserve amount of `lnd`. In my case, funding an account left <100k anchor reserves(maximum we keep as anchor reserve) of on-chain funds in the `lnd`'s wallet.

**Comment by guggero** [comment]
We use the `walletrpc.SendOutputs` RPC call in `lnd`, so I think this was solved by https://github.com/lightningnetwork/lnd/pull/7631 (which will be in 0.17).
