### ISSUE TITLE
feature request: QuoteOrder

### ISSUE THREAD

**Issue by jamaljsr** [lightninglabs/pool#96]
I'm adding an order form to Terminal and would like to display some of the same information in the UI that is presented when submitting an order from the CLI:

```
-- Order Details --
Bid Amount: 0.02 BTC
Bid Duration: 2016
Total Premium (paid to maker): 0.00019998 BTC
Rate Fixed: 4960
Rate Per Block: 0.000004960 (0.0004960%)
Execution Fee:  0.00002001 BTC
Max batch fee rate: 300 sat/kw
Max chain fee: 0.000039 BTC
Confirm order (yes/no):
```

Most of this information, I am able to calculate in the web app with relatively little code. For example, I've already implemented the code to convert from interest rate to the rate per block. The challenge I am currently facing is calculating the "Max chain fee" given the `--max_batch_fee_rate`. I have traced how this is done in the `pool` CLI. It calls [EstimateTraderFee](https://github.com/lightninglabs/pool/blob/c54b2df51efa9a102a3cfe3ec38c1a31120f6649/order/tradingfees.go#L68) which uses constants from `poolscript`, `lnd`, and `btcd` to determine the bytes of this order's transaction in the batch. 

I started down the path of copying all of these constants into my JS code, then realized how much needed to be duplicated. My concern is not just how much effort this would be for me, but I am also considering the usability of the GRPC API for future devs. I would image that they will also run into this same issue and need to duplicate this code in their apps. This feels a bit wasteful for consumers of the API.

With all of that said, I'd like to request the ability to fetch the same order details above as a quote without actually submitting the order. I'm imagining there would be a `QuoteOrder` endpoint which takes the exact same args as `SubmitOrder`, but the response would be something like this:

```
{
  "premium": "19998",
  "rate_fixed": 4960,
  "rate_per_block_pct": "0.0004960",
  "execution_fee": "2001",
  "max_batch_fee_rate": 300,
  "max_chain_fee": "3900"
}
```

**Comment by halseth** [comment]
This still wanted/needed?

**Comment by jamaljsr** [comment]
Yes, this is still needed for the UI to be able to display accurate fees before placing an order.
